#!/usr/bin/env Rscript

# Drake Wagner
# dbw2tn
# dbw2tn@virginia.edu
# setwd('~/git/stat-6021')                  # LINUX
# setwd('C:\\Users\\dwagn\\git\\stat-6021') # WINDOWS

library('ggplot2')

dia <- read.csv('diamonds4.csv')

ggplot(data=dia, aes(x=carat, y=price)) + 
  geom_point() + 
  geom_smooth(method='lm', formula= y~x, se=FALSE, col='red')

attach(dia)
slr_model_1 <- lm(price~carat)
summary(slr_model_1)

ggplot(data=dia, aes(x=slr_model_1$fitted.values, y=slr_model_1$residuals)) +
  geom_point() +
  labs(title='Residuals Against Fitted Values') +
  ylab('Residuals') +
  xlab('Fitted values')

log_price <- log(price)
slr_model_2 <- lm(log_price~carat)
summary(slr_model_2) # significant!

ggplot(data=dia, aes(x=slr_model_2$fitted.values, y=slr_model_2$residuals)) +
  geom_point() +
  labs(title='Log Residuals Against Fitted Values') +
  ylab('Log Res') +
  xlab('Log FV')

acf(slr_model_2$residuals, main="ACF of Res") # ACF of residuals


########
# Price in relation to carat and color
crt_col_int <- lm(price~carat*color)
summary(crt_col_int)
# All colors except for Color E are significant, suggesting that carat and color
# are jointly correlated with the price of the diamond.

